### PR TITLE
Removing duplicate viewport tag

### PR DESCRIPTION
**Pull request by grahamkennery**

### CODE REVIEW

**Comment by grahamkennery** [comment]
This is a quality pull request! 10/10 would recommend.

**Review by Jspsun — CHANGES_REQUESTED** [review]
I'm thinking that it might be best to merge the two meta tags and just have one as  `<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, shrink-to-fit=no">` deleting just the bottom one causes some issues on mobile. Good catch tho I kindof copypasta'd without thinking. For once I catch something in a code review :^)

**Comment by grahamkennery** [comment]
@Jspsun Pull request updated ;)

**Review by Jspsun — APPROVED** [review]

**Comment by Jspsun** [comment]
Looks dopeeee

**Pull request merged**
